apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pft-be-kyc-hpa
  namespace: pft-be-kyc
  labels:
    app: pft-be-kyc
spec:
  scaleTargetRef:
    apiVersion: apps/v1  
    kind: Deployment
    name: pft-be-kyc-app
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0